/* XPM */
static const char * browser_left_xpm[] = {
"92 92 156 2",
"  	c None",
". 	c #6A6A6A",
"+ 	c #888888",
"@ 	c #949494",
"# 	c #9A9A9A",
"$ 	c #999999",
"% 	c #989898",
"& 	c #8E8E8E",
"* 	c #7A7A7A",
"= 	c #909090",
"- 	c #979797",
"; 	c #969696",
"> 	c #818181",
", 	c #828282",
"' 	c #919191",
") 	c #6C6C6C",
"! 	c #8B8B8B",
"~ 	c #939393",
"{ 	c #777777",
"] 	c #8A8A8A",
"^ 	c #959595",
"/ 	c #767676",
"( 	c #7F7F7F",
"_ 	c #8D8D8D",
": 	c #858585",
"< 	c #898989",
"[ 	c #929292",
"} 	c #747474",
"| 	c #848484",
"1 	c #8F8F8F",
"2 	c #787878",
"3 	c #838383",
"4 	c #3D3D3D",
"5 	c #8C8C8C",
"6 	c #454545",
"7 	c #444444",
"8 	c #7D7D7D",
"9 	c #5B5B5B",
"0 	c #414141",
"a 	c #505050",
"b 	c #646464",
"c 	c #727272",
"d 	c #5D5D5D",
"e 	c #656565",
"f 	c #525252",
"g 	c #606060",
"h 	c #6B6B6B",
"i 	c #4C4C4C",
"j 	c #626262",
"k 	c #4A4A4A",
"l 	c #5F5F5F",
"m 	c #737373",
"n 	c #878787",
"o 	c #7E7E7E",
"p 	c #6F6F6F",
"q 	c #464646",
"r 	c #595959",
"s 	c #707070",
"t 	c #868686",
"u 	c #545454",
"v 	c #A6A6A6",
"w 	c #9D9D9D",
"x 	c #7C7C7C",
"y 	c #4E4E4E",
"z 	c #A8A8A8",
"A 	c #B1B1B1",
"B 	c #A5A5A5",
"C 	c #5A5A5A",
"D 	c #5E5E5E",
"E 	c #757575",
"F 	c #B6B6B6",
"G 	c #BBBBBB",
"H 	c #7B7B7B",
"I 	c #6D6D6D",
"J 	c #474747",
"K 	c #585858",
"L 	c #A1A1A1",
"M 	c #B5B5B5",
"N 	c #C1C1C1",
"O 	c #C3C3C3",
"P 	c #A9A9A9",
"Q 	c #686868",
"R 	c #9B9B9B",
"S 	c #C9C9C9",
"T 	c #C7C7C7",
"U 	c #ABABAB",
"V 	c #4D4D4D",
"W 	c #BEBEBE",
"X 	c #CACACA",
"Y 	c #D0D0D0",
"Z 	c #CBCBCB",
"` 	c #ADADAD",
" .	c #797979",
"..	c #5C5C5C",
"+.	c #B9B9B9",
"@.	c #D1D1D1",
"#.	c #D2D2D2",
"$.	c #CDCDCD",
"%.	c #B3B3B3",
"&.	c #6E6E6E",
"*.	c #616161",
"=.	c #484848",
"-.	c #565656",
";.	c #9F9F9F",
">.	c #C4C4C4",
",.	c #CECECE",
"'.	c #D4D4D4",
").	c #D5D5D5",
"!.	c #C6C6C6",
"~.	c #B8B8B8",
"{.	c #A3A3A3",
"].	c #494949",
"^.	c #4F4F4F",
"/.	c #666666",
"(.	c #AFAFAF",
"_.	c #C0C0C0",
":.	c #CCCCCC",
"<.	c #D7D7D7",
"[.	c #D3D3D3",
"}.	c #AEAEAE",
"|.	c #9E9E9E",
"1.	c #4B4B4B",
"2.	c #AAAAAA",
"3.	c #BCBCBC",
"4.	c #D9D9D9",
"5.	c #D8D8D8",
"6.	c #CFCFCF",
"7.	c #A7A7A7",
"8.	c #DADADA",
"9.	c #C8C8C8",
"0.	c #B4B4B4",
"a.	c #B2B2B2",
"b.	c #808080",
"c.	c #535353",
"d.	c #D6D6D6",
"e.	c #C5C5C5",
"f.	c #BFBFBF",
"g.	c #515151",
"h.	c #BABABA",
"i.	c #A4A4A4",
"j.	c #717171",
"k.	c #A2A2A2",
"l.	c #B7B7B7",
"m.	c #676767",
"n.	c #696969",
"o.	c #B0B0B0",
"p.	c #636363",
"q.	c #BDBDBD",
"r.	c #434343",
"s.	c #C2C2C2",
"t.	c #555555",
"u.	c #3A3A3A",
"v.	c #575757",
"w.	c #9C9C9C",
"x.	c #A0A0A0",
"y.	c #ACACAC",
"                                                                                                                                                                                        ",
"                  . + @ # # $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ # % & *                     ",
"              . = $ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - % ; >                 ",
"            , % ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; - - ' )             ",
"          ! - ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; - ~ {           ",
"        ] ; ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ; ' /         ",
"      ( ^ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ ^ _         ",
"      ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ :       ",
"    < ~ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ ~ & }     ",
"    [ ' [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ ' [ [ ' [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ ' ~ |     ",
"  ( ' = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = ' 1 2 [ = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = ' <     ",
"  < = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = 3 4 @ = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = ' 5 /   ",
"  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 _ 6 7 ~ 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 8   ",
"  & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & 9 0 a ' & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & 1 (   ",
"b & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & _ & c 0 a d = & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & 1 (   ",
"e _ 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 _ , 6 f g h & 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 & (   ",
"e 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 i a j c * _ 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 _ (   ",
"b ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! _ 9 k l m | n ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! 5 o   ",
"e ! ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] 5 p q r s t ; ~ ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] 5 8   ",
"b ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ( q u . 3 % v w + ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ! x   ",
"b < + + + + + + + + + + + + + + + + + + + + + + + + + + + + + < < i y b 8 ; z A B n + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + ] x   ",
"b + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + 5 C k D E & v F G B t + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + < H   ",
"b n n n n n n n n n n n n n n n n n n n n n n n n n n n n n < I J K p + L M N O P : n n n n n n n n n n n n n n n n n n n n n n n n n n n n n n n n n n n n n n n n n n n n n n n + H   ",
"j t t t t t t t t t t t t t t t t t t t t t t t t t t t t n 8 q f Q , R A N S T U | t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t n *   ",
"j t t t t t t t t t t t t t t t t t t t t t t t t t t t t t V V j H @ U W X Y Z ` 3 t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t n  .  ",
"j : | | | | | | | | | | | | | | | | | | | | | | | | | | < r k ..} _ B +.T @.#.$.%.o x { m s &.I I I I I I I I I I I I I I I I I I I I I I I I I I I I I p : | | | | | | | | | | | :  .  ",
"*.| | | | | | | | | | | | | | | | | | | | | | | | | 3 t . =.-.I n ;.%.>.,.'.).Y !.~.{.5  .h j D d d d d d d d d d d d d d d d d d d d d d d d d d ....K K : | | | | | | | | | | | | 2   ",
"*.3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 | * ].^./.( $ (._.:.'.<.<.[.Z W }.|.1 | ( x * * * * * * * * * * * * * * * * * * * * * * * * * H 2 } . | 3 3 3 3 3 3 3 3 3 3 3 | 2   ",
"*., , , , , , , , , , , , , , , , , , , , , , , , , 3 ^.1.g  .[ 2.3.S #.<.4.5.).6.!.3.A 7.;.R $ % % % % % % % % % % % % % % % % % % % % % % % % % % ^ 1 8 , , , , , , , , , , , , 3 {   ",
"*., , , , , , , , , , , , , , , , , , , , , , , > t C =.r c ! {.~.T Y ).5.8.4.<.[.,.9.N G F 0.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.a.}.7.& > , , , , , , , , , , , , /   ",
"g > b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.3 Q ].c.h : w %.O ,.'.<.4.4.4.5.d.[.Y $.X T T !.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.>.N +.$ ( b.b.b.b.b.b.b.b.b.b.b.> E   ",
"g b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.> { 1.V b 8 ; ` f.Z [.d.4.4.4.4.4.5.<.d.'.[.#.#.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.Y $.>.L ( b.b.b.b.b.b.b.b.b.b.b.> E   ",
"l ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( g.=.D { = z h.S @.d.5.4.4.4.4.4.4.4.4.4.5.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.#.S i.8 ( ( ( ( ( ( ( ( ( ( ( b.}   ",
"l o o o o o o o o o o o o o o o o o o o o o , 9 J K j.] k.l.!.Y ).5.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.).Z v x o o o o o o o o o o o ( m   ",
"D 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 b.m.=.g.n., # o.N :.#.d.5.5.5.5.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.5.'.Z v H 8 8 8 8 8 8 8 8 8 8 8 o c   ",
"D 8 x x x x x x x x x x x x x x x x x x o } V k p.x ^ U q.X #.d.5.5.5.5.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.5.'.Z v H x x x x x x x x x x x 8 c   ",
"D x x x x x x x x x x x x x x x x x x x H u q ..E & B +.T Y '.<.5.5.5.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.5.'.Z B * x x x x x x x x x x x x j.  ",
"D H H H H H H H H H H H H H H H H H H ( D 6 -.&.+ ;.0.>.,.'.<.5.5.5.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.5.'.Z B  .H H H H H H H H H H H x j.  ",
"d * * * * * * * * * * * * * * * * * 8 m.=.^.m.b.% }.f.X @.).<.<.<.<.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.<.[.X B 2 * * * * * * * * * * * H s   ",
"d  . . . . . . . . . . . . . . . .* j.y J g  .[ P G 9.Y '.<.<.<.<.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.<.[.X B {  . . . . . . . . . . .* p   ",
"d  .2 2 2 2 2 2 2 2 2 2 2 2 2 2  .2 -.r.C m 5 i.l.e.,.'.d.<.<.<.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.<.[.X i.{ 2 2 2 2 2 2 2 2 2 2 2  .p   ",
"..2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 * D r.u ) : |.a.s.:.#.d.<.<.<.<.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.<.[.X i.E 2 2 2 2 2 2 2 2 2 2 2 2 &.  ",
"..{ { { { { { { { { { { { { {  .m.=.V /.( % }.f.X @.).<.<.<.<.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.<.[.X i.E { { { { { { { { { { { 2 &.  ",
"../ / / / / / / / / / / / / { p ^.7 D { = 7.h.T 6.[.d.d.d.d.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.d.#.S k.} / / / / / / / / / / / { I   ",
"9 E E E E E E E E E E E E E } -.4 t.&.< L M >.$.#.).d.d.d.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.d.#.S k.m E E E E E E E E E E E / )   ",
"9 E } } } } } } } } } } } { g u.].j 8 % }._.Z @.).d.d.d.d.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.d.#.S k.c } } } } } } } } } } } E )   ",
"9 } } } } } } } } } } } } } ) g.y h n k.l.!.6.[.).d.).d.d.<.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.<.d.@.9.k.j.} } } } } } } } } } } } h   ",
"C m m m m m m m m m m m m m E m.v.I 5 v h.9.6.'.).).).d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.).@.9.L j.m m m m m m m m m m m } h   ",
"C c c c c c c c c c c c c c c c m.. ] i.~.!.6.[.).).).d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.).@.9.L s c c c c c c c c c c c m .   ",
"C j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.I h ( w.a.s.:.@.'.).).).d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.).@.9.L p j.j.j.j.j.j.j.j.j.j.j.c n.  ",
"r s s s s s s s s s s s s s s s j.n.j.1 7.h.T ,.[.).).).).d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.).@.9.x.&.s s s s s s s s s s s j.Q   ",
"r s s s s s s s s s s s s s s s p s h  .- ` W S Y [.'.).'.).).d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.).Y T x.I s s s s s s s s s s s s Q   ",
"r p &.&.&.&.&.&.&.&.&.&.&.&.&.&.&.p ) ) , |.a.N Z Y [.'.'.'.).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).'.Y T x.) &.&.&.&.&.&.&.&.&.&.&.p m.  ",
"K &.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.n.j.! i.l.>.$.@.'.'.'.'.).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).'.Y T ;.) &.&.&.&.&.&.&.&.&.&.&.p m.  ",
"K I I I I I I I I I I I I I I I I I I &././ @ 2.G T ,.#.'.'.'.'.).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).'.Y T ;.h I I I I I I I I I I I &./.  ",
"K I ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) I . o $ (.f.S 6.[.[.'.[.'.'.).'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.).'.6.!.;.. ) ) ) ) ) ) ) ) ) ) ) I /.  ",
"v.) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) m.) t x.%.s.Z Y [.[.[.[.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.[.6.!.;.n.) ) ) ) ) ) ) ) ) ) ) ) e   ",
"v.h . . . . . . . . . . . . . . . . . . . h b } 1 v ~.e.$.@.[.[.[.[.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.[.6.!.|.Q . . . . . . . . . . . h b   ",
"v.. . . . . . . . . . . . . . . . . . . . . h p.* - y.3.9.,.@.[.[.[.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.[.6.!.|.Q . . . . . . . . . . . h b   ",
"-.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.Q Q > w.o.f.S ,.@.#.#.#.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.#.,.e.w m.n.n.n.n.n.n.n.n.n.n.n.. p.  ",
"-.Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q p.&.< k.M O Z 6.#.#.#.#.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.#.,.e.w /.Q Q Q Q Q Q Q Q Q Q Q Q j   ",
"-.Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q m.Q *.{ [ z +.e.:.Y #.#.#.#.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.[.#.,.e.w e Q Q Q Q Q Q Q Q Q Q Q Q j   ",
"t.m./././././././././././././././././././././././.m.j 8 % }.q.T ,.Y #.#.#.[.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.[.#.,.>.w b /././././././././././.m.*.  ",
"t./././././././././././././././././././././././././.j n.: |.a._.S ,.@.@.#.#.#.@.#.#.#.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.Y :.s.# p././././././././././././.g   ",
"t.e e e e e e e e e e e e e e e e e e e e e e e e e e g j._ i.F O Z 6.@.@.@.@.@.@.6.6.$.$.:.Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z !.q.- p.e e e e e e e e e e e /.g   ",
"u b b b b b b b b b b b b b b b b b b b b b b b b b b b D  .@ P h.!.:.6.@.@.@.Y ,.:.X T >.O s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.N q.M ' j b b b b b b b b b b b b l   ",
"u p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.j > R (.W 9.$.Y @.Y ,.l.1 & 5 ] < n n t t t t t t t t t t t t t t t t t t t t t t t t t t | b.s j p.p.p.p.p.p.p.p.p.p.p.p.D   ",
"u p.j j j j j j j j j j j j j j j j j j j j j j j j j j p.D . + L %.N S $.6.6.X @ g p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.j j j j j j j j j j j j p.D   ",
"c.j j j j j j j j j j j j j j j j j j j j j j j j j j j j j ..E 1 v ~.O Z ,.:.T [ l j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j d   ",
"c.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.j ..8 ; U G e.Z :.>.& l *.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.d   ",
"c.g g g g g g g g g g g g g g g g g g g g g g g g g g g g g g l e | w A f.!.9.N ! D g g g g g g g g g g g g g g g g g g g g g g g g g g g g g g g g g g g g g g g g g g g g g g g g ..  ",
"c.g g g g g g g g g g g g g g g g g g g g g g g g g g g g g g g C I 5 {.M N e.W < d g g g g g g g g g g g g g g g g g g g g g g g g g g g g g g g g g g g g g g g g g g g g g g g g 9   ",
"f l D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D l C  .[ z l.f.G n ..D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D l C   ",
"f D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D d D 9 > $ y.F M | 9 D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D r   ",
"f d d d d d d d d d d d d d d d d d d d d d d d d d d d d d d d d d 9 /.n w ` }., 9 d d d d d d d d d d d d d d d d d d d d d d d d d d d d d d d d d d d d d d d d d d d d d d d d r   ",
"g.....................................................................K m & ;.v 8 C ................................................................................................K   ",
"a 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 v.x 1 $ { r 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 v.  ",
"a C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C ..o ] s r C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C -.  ",
"  C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C v.e H Q r C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C C -.  ",
"  r r r r r r r r r r r r r r r r r r r r r r r r r r r r r r r r r r r r r t.m.D r r r r r r r r r r r r r r r r r r r r r r r r r r r r r r r r r r r r r r r r r r r r r r r r r t.  ",
"  K K K K K K K K K K K K K K K K K K K K K K K K K K K K K K K K K K K K K K g.t.K K K K K K K K K K K K K K K K K K K K K K K K K K K K K K K K K K K K K K K K K K K K K K K K K c.  ",
"  u v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.J K v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.-.    ",
"  a v.v.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.v.v.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.v.u     ",
"    t.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.t.g.    ",
"    a t.t.t.t.t.t.t.t.t.t.t.t.t.t.t.t.t.t.t.t.t.t.t.t.t.t.t.t.t.t.t.t.t.t.t.t.t.t.t.t.t.t.t.t.t.t.t.t.t.t.t.t.t.t.t.t.t.t.t.t.t.t.t.t.t.t.t.t.t.t.t.t.t.t.t.t.t.t.t.t.t.t.t.t.t.c.      ",
"      f u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u c.^.      ",
"        c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.a         ",
"          g.f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f a           ",
"            g.f g.f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f g.f f a             ",
"              ^.g.g.a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a g.g.a                 ",
"                  y a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a ^.i                   ",
"                        i V V y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y V i                           "};
