/* XPM */
static const char* browser_right_xpm[] = {
"77 77 178 2",
"  	c None",
". 	c #8691A3",
"+ 	c #929DB2",
"@ 	c #94A0B5",
"# 	c #8C96AC",
"$ 	c #B3C1DA",
"% 	c #ACB9D3",
"& 	c #A4B1CA",
"* 	c #BFCEE9",
"= 	c #A1ADC5",
"- 	c #B9C7E3",
"; 	c #B6C5E0",
"> 	c #CBDAF6",
", 	c #939FB5",
"' 	c #AFBDD9",
") 	c #CBDBF7",
"! 	c #C0CFEB",
"~ 	c #D2E2FE",
"{ 	c #B6C5E1",
"] 	c #D3E3FF",
"^ 	c #C6D5F1",
"/ 	c #BFCEEA",
"( 	c #D3E2FF",
"_ 	c #B9C9E5",
": 	c #CEDDFA",
"< 	c #6C7383",
"[ 	c #C3D2EE",
"} 	c #A3B0C5",
"| 	c #C0CFE7",
"1 	c #9FABC2",
"2 	c #BDCDE9",
"3 	c #D3E1FF",
"4 	c #8892A6",
"5 	c #CBD8E7",
"6 	c #ECF9FF",
"7 	c #B5C2D4",
"8 	c #C9D7F5",
"9 	c #9FABC3",
"0 	c #DFE4EF",
"a 	c #FEFFFF",
"b 	c #C3CEE3",
"c 	c #C3D3EF",
"d 	c #D2E0FE",
"e 	c #AEBBD6",
"f 	c #E4E9F3",
"g 	c #FFFFFF",
"h 	c #C9D4E8",
"i 	c #BFCFEB",
"j 	c #CAD8F6",
"k 	c #B5C4E0",
"l 	c #E5EBF5",
"m 	c #CAD7EB",
"n 	c #C4D3EF",
"o 	c #D0DDFB",
"p 	c #B9C8E4",
"q 	c #E3ECF6",
"r 	c #F7FFFF",
"s 	c #CBD9EE",
"t 	c #CCDAF6",
"u 	c #BCCDE9",
"v 	c #DAEAF7",
"w 	c #E9F8FF",
"x 	c #C9D9F0",
"y 	c #C5D4F0",
"z 	c #CDDBF7",
"A 	c #D5E4F7",
"B 	c #DFEEFF",
"C 	c #C7D6F0",
"D 	c #C1D0EC",
"E 	c #CAD8F4",
"F 	c #CEDDF8",
"G 	c #D5E4FF",
"H 	c #C9D7F3",
"I 	c #C5D3EF",
"J 	c #C7D5F1",
"K 	c #C4D2EE",
"L 	c #C2D0EC",
"M 	c #C6D4F0",
"N 	c #C8D6F2",
"O 	c #CBD9F5",
"P 	c #CDDAF8",
"Q 	c #CEDCFA",
"R 	c #CFDDFA",
"S 	c #CEDDF9",
"T 	c #CCDCF7",
"U 	c #C4D3EE",
"V 	c #B7C6E0",
"W 	c #ABB8D0",
"X 	c #8A94A8",
"Y 	c #C1CFEB",
"Z 	c #BECDE8",
"` 	c #BCCAE5",
" .	c #B9C8E2",
"..	c #B6C5DF",
"+.	c #B4C2DC",
"@.	c #B0BED7",
"#.	c #ACB9D1",
"$.	c #A8B4CC",
"%.	c #A3B0C6",
"&.	c #9DA9BF",
"*.	c #8D97AB",
"=.	c #7A8295",
"-.	c #686E7E",
";.	c #4D525C",
">.	c #4A4F5A",
",.	c #7A8395",
"'.	c #494E58",
").	c #474C56",
"!.	c #464B55",
"~.	c #BFCDE9",
"{.	c #8D97AC",
"].	c #464B54",
"^.	c #BCC9E4",
"/.	c #BBC9E4",
"(.	c #B8C6E0",
"_.	c #B7C5E0",
":.	c #B8C6E1",
"<.	c #BECEE9",
"[.	c #B5C3DC",
"}.	c #B3C1DB",
"|.	c #B5C3DD",
"1.	c #BDCBE6",
"2.	c #7A8396",
"3.	c #B3C1D9",
"4.	c #B2BFD8",
"5.	c #B3C0DA",
"6.	c #BBCBE7",
"7.	c #BAC8E3",
"8.	c #B2BFD7",
"9.	c #B1BED5",
"0.	c #B8C7E2",
"a.	c #BDCCE7",
"b.	c #B0BBD2",
"c.	c #AFBBD1",
"d.	c #AFBCD3",
"e.	c #B5C3DE",
"f.	c #99A4B8",
"g.	c #98A3B8",
"h.	c #9BA6BB",
"i.	c #AFBDD6",
"j.	c #BCCBE7",
"k.	c #A8B5CC",
"l.	c #9DA9C0",
"m.	c #7D8595",
"n.	c #7A8293",
"o.	c #7F8798",
"p.	c #9EA9C1",
"q.	c #B6C4DE",
"r.	c #A3B0C7",
"s.	c #7F899B",
"t.	c #7D8596",
"u.	c #7B8495",
"v.	c #7A8393",
"w.	c #7C8596",
"x.	c #8C96AA",
"y.	c #B0BFD9",
"z.	c #7B8396",
"A.	c #B7C6E1",
"B.	c #484E58",
"C.	c #ACBAD4",
"D.	c #A4B0C7",
"E.	c #4A505A",
"F.	c #B5C4DF",
"G.	c #9EA9C0",
"H.	c #4D535E",
"I.	c #ABB9D1",
"J.	c #515662",
"K.	c #A6B2C9",
"L.	c #AEBBD5",
"M.	c #A0ACC2",
"N.	c #A9B5CE",
"O.	c #939DB2",
"P.	c #9CA7BF",
"Q.	c #81899D",
"R.	c #6C7484",
"S.	c #798194",
"T.	c #484D57",
"U.	c #4E525D",
"                                                                                                                                                          ",
"                                                                                                                                                          ",
"                                                                                                                                                          ",
"                                                                                                                                                          ",
"                                                                                                                                                          ",
"                                                                                                                                                          ",
"                                                                              .                                                                           ",
"                                                                              + @                                                                         ",
"                                                                              # $ @                                                                       ",
"                                                                              # % $ @                                                                     ",
"                                                                              # & * $ @                                                                   ",
"                                                                              # = - * $ @                                                                 ",
"                                                                              # = ; > * $ ,                                                               ",
"                                                                              # = ' ) > * $ ,                                                             ",
"                                                                              # = ' ! ~ > * $ ,                                                           ",
"                                                                              # = ' { ] ~ > * $ ,                                                         ",
"                                                                              # = ' { ^ ] ~ > * $ ,                                                       ",
"                                                                              # = ' { / ( ] ~ > * $ @                                                     ",
"                                                                              # = ' { _ : ( ] ~ > * $ @                                                   ",
"                                                                            < # = ' { _ [ ( ( ] ~ > * $ @                                                 ",
"                  } | | | | | | | | | | | | | | | | | | | | | | | | | | | | | 1 = ' { _ 2 3 ( ( ] ~ > * $ ,                                               ",
"                  4 5 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 7 ' { _ 2 8 3 ( ( ] ~ > * $ ,                                             ",
"                  4 9 0 a a a a a a a a a a a a a a a a a a a a a a a a a a a a a b { _ 2 c d 3 ( ( ] ~ > * $ ,                                           ",
"                  4 9 e f g g g g g g g g g g g g g g g g g g g g g g g g g g g g g h _ 2 i j d 3 ( ( ] ~ > * $ ,                                         ",
"                  4 9 e k l g g g g g g g g g g g g g g g g g g g g g g g g g g g g g m 2 i n o d 3 ( ( ] ~ > * $ ,                                       ",
"                  4 9 e k p q r r r r r r r r r r r r r r r r r r r r r r r r r r r r r s i ! t o d 3 ( ( ] ~ > * $ @                                     ",
"                  4 9 e k p u v w w w w w w w w w w w w w w w w w w w w w w w w w w w w w x ! y z o d 3 ( ( ] ~ > * $ @                                   ",
"                  4 9 e k p u i A B B B B B B B B B B B B B B B B B B B B B B B B B B B B B C D E z o d 3 ( ( ] ~ > * $ @                                 ",
"                  4 9 e k p u i ! F G G G G G G G G G G G G G G G G G G G G G G G G G G G G G ^ n E z o d 3 ( ( ] ~ > * $ ,                               ",
"                  4 9 e k p u i ! D H t t t t t t t t t t t t t t t t t t t t t t t t t t t t t I J E z o d 3 ( ( ] ~ > * $ ,                             ",
"                  4 9 e k p u i ! D D K K K K K K K K K K K K K K K K K K K K K K K K K K K K K K K J E z o d 3 ( ( ] ~ > * $ ,                           ",
"                  4 9 e k p u i ! D D L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L K J E z o d 3 ( ( ] ~ > * $ ,                         ",
"                  4 9 e k p u i ! D D L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L K J E z o d 3 ( ( ] ~ > * $ ,                       ",
"                  4 9 e k p u i ! D D L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L K J E z o d 3 ( ( ] ~ > * $ @                     ",
"                  4 9 e k p u i ! D D L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L K M N O P Q R R S S T U V W X                   ",
"                  4 9 e k p u i ! D D L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L Y Z `  ...+.@.#.$.%.&.*.=.-.;.                  ",
"                  4 9 e k p u i ! D D L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L Y Z `  ...+.@.#.$.%.&.*.=.-.>.                    ",
"                  4 9 e k p u i ! D D L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L Y Z `  ...+.@.#.$.%.&.*.,.-.'.                      ",
"                  4 9 e k p u i ! D D L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L Y Z `  ...+.@.#.$.%.&.*.,.-.).                        ",
"                  4 9 e k p u i ! D D L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L Y Z `  ...+.@.#.$.%.&.*.,.-.!.                          ",
"                  4 9 e k p u i ! D ~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.Y Z `  ...+.@.#.$.%.&.{.,.-.].                            ",
"                  4 9 e k p u i ! ^././././././././././././././././././././././././././././.` / * `  ...+.@.#.$.%.&.{.,.-.].                              ",
"                  4 9 e k p u i (._._._._._._._._._._._._._._._._._._._._._._._._._._._._.:.<.! `  ...+.@.#.$.%.&.{.,.-.!.                                ",
"                  4 9 e k p u [.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.|.2 ! 1. ...+.@.#.$.%.&.{.2.-.!.                                  ",
"                  4 9 e k p 3.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.5.6.i ! 7...+.@.#.$.%.&.{.2.-.!.                                    ",
"                  4 9 e k 8.9.9.9.9.9.9.9.9.9.9.9.9.9.9.9.9.9.9.9.9.9.9.9.9.9.9.9.9.8.0.2 i a...+.@.#.$.%.&.{.2.-.].                                      ",
"                  4 9 e b.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.d.e._ 2 i (.+.@.#.$.%.&.{.2.-.].                                        ",
"                  4 9 f.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.h.i.{ _ 2 j.+.@.#.k.%.l.{.2.-.].                                          ",
"                  4 m.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.o.p.' { _ 2 q.@.#.k.r.l.{.2.-.].                                            ",
"                  s.t.u.v.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.w.x.= ' { _ 2 y.#.k.r.l.{.z.-.].                                              ",
"                                                                            ).# = ' { _ A.#.k.r.l.{.z.-.].                                                ",
"                                                                            B.# = ' { _ C.k.D.l.{.z.-.!.                                                  ",
"                                                                            E.# = ' { F.k.D.G.{.z.-.!.                                                    ",
"                                                                            H.# = ' { I.D.G.{.z.-.].                                                      ",
"                                                                            J.# = ' { K.G.{.z.-.].                                                        ",
"                                                                              # = ' L.G.{.z.-.].                                                          ",
"                                                                              # = ' M.{.z.-.].                                                            ",
"                                                                              # = N.{.z.-.].                                                              ",
"                                                                              # = O.z.-.].                                                                ",
"                                                                              # P.z.-.!.                                                                  ",
"                                                                              # Q.-.!.                                                                    ",
"                                                                              # R.).                                                                      ",
"                                                                              S.T.                                                                        ",
"                                                                              U.                                                                          ",
"                                                                                                                                                          ",
"                                                                                                                                                          ",
"                                                                                                                                                          ",
"                                                                                                                                                          ",
"                                                                                                                                                          ",
"                                                                                                                                                          ",
"                                                                                                                                                          ",
"                                                                                                                                                          ",
"                                                                                                                                                          ",
"                                                                                                                                                          ",
"                                                                                                                                                          ",
"                                                                                                                                                          ",
"                                                                                                                                                          "};
