/* XPM */
static const char* browser_left_xpm[] = {
"77 77 156 2",
"  	c None",
". 	c #757E91",
"+ 	c #A6B3CD",
"@ 	c #676E7D",
"# 	c #AFBBD5",
"$ 	c #626977",
"% 	c #BCCAE6",
"& 	c #9BA7BE",
"* 	c #C4D3EF",
"= 	c #909CB0",
"- 	c #CBDAF6",
"; 	c #AEBBD2",
"> 	c #D9E8FD",
", 	c #A9B7CD",
"' 	c #A6B2CC",
") 	c #CBDBEE",
"! 	c #A3B0C7",
"~ 	c #DEEEFF",
"{ 	c #BAC8DF",
"] 	c #D2E2F5",
"^ 	c #AEBCD5",
"/ 	c #BECCE4",
"( 	c #DDEDFF",
"_ 	c #B8C6E0",
": 	c #CEDCF3",
"< 	c #B3C1DB",
"[ 	c #DBEBFF",
"} 	c #BDCBE4",
"| 	c #D2E1F9",
"1 	c #B8C6E1",
"2 	c #9CA7BB",
"3 	c #C0CFE7",
"4 	c #6C7482",
"5 	c #D9E9FF",
"6 	c #C3D1ED",
"7 	c #C3CDD7",
"8 	c #ECF9FF",
"9 	c #AEBBCB",
"0 	c #515763",
"a 	c #D6E6FF",
"b 	c #C0CEEA",
"c 	c #D1D7E4",
"d 	c #FEFFFF",
"e 	c #C3CBD9",
"f 	c #8E99AD",
"g 	c #C8D7F2",
"h 	c #D7DEEA",
"i 	c #FFFFFF",
"j 	c #CCD5E4",
"k 	c #A0AEC4",
"l 	c #D2E1FD",
"m 	c #C1CFEB",
"n 	c #D9DFED",
"o 	c #CFD8E7",
"p 	c #ADBBD4",
"q 	c #C9D8F4",
"r 	c #BECDE8",
"s 	c #D7E2F1",
"t 	c #F7FFFF",
"u 	c #D1DBEC",
"v 	c #B2C0DA",
"w 	c #CEDDF9",
"x 	c #D2E1F2",
"y 	c #E9F8FF",
"z 	c #CFDDF0",
"A 	c #B8C5E1",
"B 	c #BFCDE9",
"C 	c #CEDCF4",
"D 	c #DFEEFF",
"E 	c #CBD9F0",
"F 	c #CBD9F5",
"G 	c #C4D2EE",
"H 	c #CAD8F3",
"I 	c #D5E4FF",
"J 	c #C9D7F1",
"K 	c #BECBE7",
"L 	c #C7D5F1",
"M 	c #C6D4F0",
"N 	c #CCDAF6",
"O 	c #C1CEEA",
"P 	c #C2D0EC",
"Q 	c #A0ACC4",
"R 	c #B4C1DC",
"S 	c #C3D2EC",
"T 	c #D1E1F6",
"U 	c #D8E7F9",
"V 	c #D8E7FA",
"W 	c #D7E7FA",
"X 	c #D6E6FA",
"Y 	c #D5E4FB",
"Z 	c #D2E2FB",
"` 	c #CFDEFA",
" .	c #CCDBF7",
"..	c #C9D7F3",
"+.	c #8E97AD",
"@.	c #7A8295",
"#.	c #8A93A8",
"$.	c #9BA5BC",
"%.	c #A7B3CB",
"&.	c #ABB8D1",
"*.	c #AEBBD5",
"=.	c #B1BED9",
"-.	c #B4C1DD",
";.	c #B6C4E0",
">.	c #B8C6E2",
",.	c #BBC9E5",
"'.	c #BDCBE7",
").	c #C0CEE9",
"!.	c #C2CFEB",
"~.	c #8C95AB",
"{.	c #8B93A9",
"].	c #8992A8",
"^.	c #8992A7",
"/.	c #BECCE8",
"(.	c #BBC9E4",
"_.	c #BCCAE4",
":.	c #BCCAE5",
"<.	c #B7C5E0",
"[.	c #BAC7E3",
"}.	c #B6C4DD",
"|.	c #B7C5DF",
"1.	c #B2BFD8",
"2.	c #B4C1DA",
"3.	c #9BA6BD",
"4.	c #ACB8D1",
"5.	c #B3C1DA",
"6.	c #B1BED5",
"7.	c #B1BFD7",
"8.	c #BAC8E4",
"9.	c #AFBDD5",
"0.	c #AFBBD1",
"a.	c #AEB9D1",
"b.	c #98A3B8",
"c.	c #97A2B8",
"d.	c #B4C2DD",
"e.	c #8F9AAC",
"f.	c #7A8293",
"g.	c #7E8697",
"h.	c #B5C3DE",
"i.	c #767E8E",
"j.	c #798192",
"k.	c #7A8393",
"l.	c #7B8394",
"m.	c #7D8596",
"n.	c #565C67",
"o.	c #B0BDD6",
"p.	c #ADB9D2",
"q.	c #ACB9D2",
"r.	c #A8B5CD",
"s.	c #9AA6BC",
"t.	c #8A94A9",
"u.	c #8893A6",
"v.	c #7C8597",
"w.	c #8A93A9",
"x.	c #606673",
"y.	c #757D8C",
"                                                                                                                                                          ",
"                                                                                                                                                          ",
"                                                                                                                                                          ",
"                                                                                                                                                          ",
"                                                                                                                                                          ",
"                                                                                                                                                          ",
"                                                                            .                                                                             ",
"                                                                          + @                                                                             ",
"                                                                        + # $                                                                             ",
"                                                                      + % & $                                                                             ",
"                                                                    + % * = $                                                                             ",
"                                                                  + % - ; = $                                                                             ",
"                                                                + % - > , = $                                                                             ",
"                                                              ' % - > ) ! = $                                                                             ",
"                                                            ' % - > ~ { ! = $                                                                             ",
"                                                          ' % - > ~ ] ^ ! = $                                                                             ",
"                                                        + % - > ~ ~ / ^ ! = $                                                                             ",
"                                                      + % - > ~ ~ ( _ ^ ! = $                                                                             ",
"                                                    + % - > ~ ~ ( : < ^ ! = $                                                                             ",
"                                                  + % - > ~ ~ ( [ } < ^ ! = $                                                                             ",
"                                                + % - > ~ ~ ( [ | 1 < ^ ! = 2 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 4                 ",
"                                              ' % - > ~ ~ ( [ 5 6 1 < ^ ! 7 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 9 0                 ",
"                                            ' % - > ~ ~ ( [ 5 a b 1 < ^ c d d d d d d d d d d d d d d d d d d d d d d d d d d d d d e f 0                 ",
"                                          ' % - > ~ ~ ( [ 5 a g % 1 < h i i i i i i i i i i i i i i i i i i i i i i i i i i i i i j k f 0                 ",
"                                        + % - > ~ ~ ( [ 5 a l m % 1 n i i i i i i i i i i i i i i i i i i i i i i i i i i i i i o p k f 0                 ",
"                                      + % - > ~ ~ ( [ 5 a l q r % s t t t t t t t t t t t t t t t t t t t t t t t t t t t t t u v p k f 0                 ",
"                                    + % - > ~ ~ ( [ 5 a l w 6 r x y y y y y y y y y y y y y y y y y y y y y y y y y y y y y z A v p k f 0                 ",
"                                  + % - > ~ ~ ( [ 5 a l w q B C D D D D D D D D D D D D D D D D D D D D D D D D D D D D D E % A v p k f 0                 ",
"                                + % - > ~ ~ ( [ 5 a l w F G H I I I I I I I I I I I I I I I I I I I I I I I I I I I I I J K % A v p k f 0                 ",
"                              ' % - > ~ ~ ( [ 5 a l w F L M N N N N N N N N N N N N N N N N N N N N N N N N N N N N N M B K % A v p k f 0                 ",
"                            ' % - > ~ ~ ( [ 5 a l w F L G G G G G G G G G G G G G G G G G G G G G G G G G G G G G G G O B K % A v p k f 0                 ",
"                          ' % - > ~ ~ ( [ 5 a l w F L G P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P O B K % A v p k f 0                 ",
"                        + % - > ~ ~ ( [ 5 a l w F L G P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P O B K % A v p k f 0                 ",
"                      + % - > ~ ~ ( [ 5 a l w F L G P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P O B K % A v p k f 0                 ",
"                    Q R S T U V W X Y Z `  ...M G P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P O B K % A v p k f 0                 ",
"                    +.@.#.$.%.&.*.=.-.;.>.,.'.).!.P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P O B K % A v p k f 0                 ",
"                      ~.@.#.$.%.&.*.=.-.;.>.,.'.).!.P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P O B K % A v p k f 0                 ",
"                        {.@.#.$.%.&.*.=.-.;.>.,.'.).!.P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P O B K % A v p k f 0                 ",
"                          ].@.#.$.%.&.*.=.-.;.>.,.'.).!.P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P O B K % A v p k f 0                 ",
"                            ^.@.#.$.%.&.*.=.-.;.>.,.'.).!.P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P O B K % A v p k f 0                 ",
"                              ^.@.#.$.%.&.*.=.-.;.>.,.'.).).B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B K % A v p k f 0                 ",
"                                ^.@.#.$.%.&.*.=.-.;.>.,.'.b /.(.(.(.(.(.(.(.(.(.(.(.(.(.(.(.(.(.(.(.(.(.(.(.(.(.(.(.(.(._.K % A v p k f 0                 ",
"                                  ^.@.#.$.%.&.*.=.-.;.>.,./.B :.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.1 % A v p k f 0                 ",
"                                    ^.@.#.$.%.&.*.=.-.;.>.,./.r [.< < < < < < < < < < < < < < < < < < < < < < < < < < < < < }.A v p k f 0                 ",
"                                      ^.@.#.$.%.&.*.=.-.;.>.% r % |.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.2.v p k f 0                 ",
"                                        ^.@.#.3.%.4.*.=.-.;.>.'.% 1 5.6.6.6.6.6.6.6.6.6.6.6.6.6.6.6.6.6.6.6.6.6.6.6.6.6.6.6.6.6.7.p k f 0                 ",
"                                          ^.@.#.3.%.4.*.=.-.;.8.% 1 < 9.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.a.k f 0                 ",
"                                            ^.@.#.3.%.4.*.=.-.;.% 1 < ^ ! b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.c.f 0                 ",
"                                              ^.@.#.3.%.4.*.=.d.>.1 < ^ ! e.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.g.0                 ",
"                                                ^.@.#.3.%.4.*.=.h.1 < ^ ! = i.j.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.k.l.m.n.                ",
"                                                  ^.@.#.3.%.4.*.=.h.< ^ ! = $                                                                             ",
"                                                    ^.@.#.3.%.4.*.v < ^ ! = $                                                                             ",
"                                                      ^.@.#.3.%.4.*.< ^ ! = $                                                                             ",
"                                                        ^.@.#.3.%.4.o.^ ! = $                                                                             ",
"                                                          ^.@.#.3.%.p.^ ! = $                                                                             ",
"                                                            ^.@.#.3.%.q.! = $                                                                             ",
"                                                              ^.@.#.3.r.! = $                                                                             ",
"                                                                ^.@.#.3.! = $                                                                             ",
"                                                                  ^.@.#.s.= $                                                                             ",
"                                                                    ].@.t.= $                                                                             ",
"                                                                      ].@.u.$                                                                             ",
"                                                                        ].v.$                                                                             ",
"                                                                          w.x.                                                                            ",
"                                                                            y.                                                                            ",
"                                                                                                                                                          ",
"                                                                                                                                                          ",
"                                                                                                                                                          ",
"                                                                                                                                                          ",
"                                                                                                                                                          ",
"                                                                                                                                                          ",
"                                                                                                                                                          ",
"                                                                                                                                                          ",
"                                                                                                                                                          ",
"                                                                                                                                                          ",
"                                                                                                                                                          ",
"                                                                                                                                                          ",
"                                                                                                                                                          "};
