/* XPM */
static const char * browser_right_xpm[] = {
"92 92 180 2",
"  	c None",
". 	c #666666",
"+ 	c #868686",
"@ 	c #939393",
"# 	c #9A9A9A",
"$ 	c #999999",
"% 	c #979797",
"& 	c #8B8B8B",
"* 	c #757575",
"= 	c #696969",
"- 	c #8F8F8F",
"; 	c #989898",
"> 	c #949494",
", 	c #7B7B7B",
"' 	c #828282",
") 	c #969696",
"! 	c #8D8D8D",
"~ 	c #919191",
"{ 	c #747474",
"] 	c #959595",
"^ 	c #8E8E8E",
"/ 	c #808080",
"( 	c #8A8A8A",
"_ 	c #848484",
": 	c #898989",
"< 	c #929292",
"[ 	c #8C8C8C",
"} 	c #878787",
"| 	c #838383",
"1 	c #909090",
"2 	c #404040",
"3 	c #414141",
"4 	c #464646",
"5 	c #525252",
"6 	c #343434",
"7 	c #5D5D5D",
"8 	c #484848",
"9 	c #303030",
"0 	c #5F5F5F",
"a 	c #353535",
"b 	c #9D9D9D",
"c 	c #7C7C7C",
"d 	c #575757",
"e 	c #3A3A3A",
"f 	c #444444",
"g 	c #858585",
"h 	c #B3B3B3",
"i 	c #717171",
"j 	c #4D4D4D",
"k 	c #5B5B5B",
"l 	c #C4C4C4",
"m 	c #B4B4B4",
"n 	c #676767",
"o 	c #727272",
"p 	c #818181",
"q 	c #CDCDCD",
"r 	c #C8C8C8",
"s 	c #ABABAB",
"t 	c #888888",
"u 	c #D1D1D1",
"v 	c #D4D4D4",
"w 	c #C1C1C1",
"x 	c #A2A2A2",
"y 	c #555555",
"z 	c #393939",
"A 	c #424242",
"B 	c #7F7F7F",
"C 	c #DADADA",
"D 	c #CFCFCF",
"E 	c #BABABA",
"F 	c #707070",
"G 	c #4C4C4C",
"H 	c #585858",
"I 	c #7E7E7E",
"J 	c #D2D2D2",
"K 	c #DCDCDC",
"L 	c #D8D8D8",
"M 	c #CBCBCB",
"N 	c #B2B2B2",
"O 	c #454545",
"P 	c #6F6F6F",
"Q 	c #7D7D7D",
"R 	c #DDDDDD",
"S 	c #DBDBDB",
"T 	c #D5D5D5",
"U 	c #C6C6C6",
"V 	c #AAAAAA",
"W 	c #5C5C5C",
"X 	c #3E3E3E",
"Y 	c #333333",
"Z 	c #D3D3D3",
"` 	c #C0C0C0",
" .	c #A0A0A0",
"..	c #797979",
"+.	c #545454",
"@.	c #6B6B6B",
"#.	c #6D6D6D",
"$.	c #D9D9D9",
"%.	c #CECECE",
"&.	c #B9B9B9",
"*.	c #4B4B4B",
"=.	c #5A5A5A",
"-.	c #E1E1E1",
";.	c #D6D6D6",
">.	c #CACACA",
",.	c #B1B1B1",
"'.	c #656565",
").	c #7A7A7A",
"!.	c #C5C5C5",
"~.	c #A8A8A8",
"{.	c #BEBEBE",
"].	c #787878",
"^.	c #535353",
"/.	c #383838",
"(.	c #3D3D3D",
"_.	c #B6B6B6",
":.	c #B8B8B8",
"<.	c #4A4A4A",
"[.	c #515151",
"}.	c #D7D7D7",
"|.	c #C9C9C9",
"1.	c #B0B0B0",
"2.	c #636363",
"3.	c #A7A7A7",
"4.	c #3C3C3C",
"5.	c #323232",
"6.	c #D0D0D0",
"7.	c #767676",
"8.	c #DFDFDF",
"9.	c #B7B7B7",
"0.	c #494949",
"a.	c #4F4F4F",
"b.	c #C7C7C7",
"c.	c #AEAEAE",
"d.	c #626262",
"e.	c #313131",
"f.	c #E0E0E0",
"g.	c #C2C2C2",
"h.	c #A5A5A5",
"i.	c #BCBCBC",
"j.	c #9C9C9C",
"k.	c #505050",
"l.	c #363636",
"m.	c #CCCCCC",
"n.	c #B5B5B5",
"o.	c #777777",
"p.	c #ADADAD",
"q.	c #606060",
"r.	c #3F3F3F",
"s.	c #A4A4A4",
"t.	c #BBBBBB",
"u.	c #737373",
"v.	c #4E4E4E",
"w.	c #3B3B3B",
"x.	c #6A6A6A",
"y.	c #ACACAC",
"z.	c #DEDEDE",
"A.	c #BFBFBF",
"B.	c #A3A3A3",
"C.	c #565656",
"D.	c #292929",
"E.	c #373737",
"F.	c #2D2D2D",
"G.	c #252525",
"H.	c #C3C3C3",
"I.	c #2C2C2C",
"J.	c #A9A9A9",
"K.	c #6C6C6C",
"L.	c #6E6E6E",
"M.	c #646464",
"N.	c #A1A1A1",
"O.	c #686868",
"P.	c #5E5E5E",
"Q.	c #AFAFAF",
"R.	c #616161",
"S.	c #BDBDBD",
"T.	c #9B9B9B",
"U.	c #595959",
"V.	c #A6A6A6",
"W.	c #9E9E9E",
"                                                                                                                                                                                        ",
"                  . + @ # # $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ # # % & *                   ",
"              = - $ % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % ; > ,               ",
"            ' ; ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) % % !             ",
"          & % ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) % ~ {         ",
"        & ) ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ) ^         ",
"      / ] > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > ] (       ",
"      > @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ _     ",
"    : @ < < < < < < < < < < < < < < < < < < < < < < < < < < < < < < < < < < < < < < < < < < < < < < < < < < < < < < < < < < < < < < < < < < < < < < < < < < < < < < < < < < < < @ [     ",
"    < ~ < < < < < < < < < < < < < < < < < < < < < < < < < < < < < < < < < < < < < < < < < < < < < ~ < < < ~ < < < < < < < < < < < < < < < < < < < < < < < < < < < < < < < < < < < < }   ",
"  | ~ 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 ~ & / - ~ 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 ~ (   ",
"  : 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 ~ ! 2 | 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 ~ &   ",
"  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - ! 3 4 & - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - [   ",
"  ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ & 5 6 7 & ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ & ",
"  ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ : = 8 9 * ! ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ : ",
"  ! [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ ! } | 0 3 a | [ ! [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ ! } ",
"  [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ + b c d e f ( [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ + ",
"  & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & g h # i j 6 k ( & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & & g ",
"  & ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( & | l m - n 4 9 o ( & ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( & g ",
"  ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( p q r s g 7 2 a p : ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( g ",
"  : t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t : / u v w x , y z A t : t t t t t t t t t t t t t t t t t t t t t t t t t t t t t : _ ",
"  t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t B u C D E ; F G 6 H t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t | ",
"  } } } } } } } } } } } } } } } } } } } } } } } } } } } } } } } } } } } } } } } } } } } } } } } } } I J K L M N ^ . O 9 P } } } } } } } } } } } } } } } } } } } } } } } } } } } } } } ' ",
"  + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + Q J R S T U V | W X Y I + + + + + + + + + + + + + + + + + + + + + + + + + + + + + ' ",
"  + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + Q J R K C Z `  ...+.z 2 } g + + + + + + + + + + + + + + + + + + + + + + + + + + + p ",
"  g _ _ _ _ _ _ _ _ _ _ _ g / @.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.g _ J K K S $.%.&.) P *.6 +.+ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ g / ",
"  _ _ _ _ _ _ _ _ _ _ _ _ _ c =.7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 W k %.-.S S S S C ;.>.,.[ '.f 9 @._ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ B ",
"  | | | | | | | | | | | | | p ).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).)...%.K S S S S S C v !.~.' k X Y c | | | | | | | | | | | | | | | | | | | | | | | | | | B ",
"  ' ' ' ' ' ' ' ' ' ' ' ' ' + # ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; % J K S S S S S S $.u {. .].^./.(._ ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' I ",
"  ' ' ' ' ' ' ' ' ' ' ' ' p & _.h h h h h h h h h h h h h h h h h h h h h h h h h h h h h h h h N T S C C C C C S C L q :.] #.<.6 [._ p ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' Q ",
"  p / / / / / / / / / / / B ! >.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.}.C C C C C C C C $.T |.1.( 2.A 9 n ' / / / / / / / / / / / / / / / / / / / / / / p c ",
"  / / / / / / / / / / / / B - }.u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u J $.C C C C C C C C C $.Z l 3./ =.4.5...p / / / / / / / / / / / / / / / / / / / / / / c ",
"  B B B B B B B B B B B B Q 1 R }.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.C C C C C C C C C C C L 6.{.b 7.[./.4.p B B B B B B B B B B B B B B B B B B B B B B , ",
"  I I I I I I I I I I I I c - 8.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.C C C C C C C C C C C C }.q 9.> #.0.6 a.' I I I I I I I I I I I I I I I I I I I I I ).",
"  Q Q Q Q Q Q Q Q Q Q Q Q , ^ 8.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.L v b.c.: d.3 e.2.B Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q ..",
"  Q c c c c c c c c c c c , ^ f.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.}.u g.h.B H e 5.* Q c c c c c c c c c c c c c c c c c c Q ..",
"  c c c c c c c c c c c c ).! f.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.L L D i.j.* k.l.4.I c c c c c c c c c c c c c c c c c c c ].",
"  , , , , , , , , , , , , ..! f.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.$.;.m.n.< @.8 6 G B , , , , , , , , , , , , , , , , , , o.",
"  ).).).).).).).).).).).).].[ 8.L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L }.Z U p.} q.r.e.q.c ).).).).).).).).).).).).).).).).).7.",
"  ........................o.& 8.L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L ;.u w s.Q d z 6 i ).................................* ",
"  ..].].].].].].].].].].].o.& 8.L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L }.;.q t.# u.v.6 w.)...].].].].].].].].].].].].].]...* ",
"  ].].].].].].].].].].].].7.( 8.L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L }.T >.m < x.4 Y <.c o.].].].].].].].].].].].].].].{ ",
"  o.o.o.o.o.o.o.o.o.o.o.o.* : 8.L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L }.Z U y.} q.r.Y W ).o.o.o.o.o.o.o.o.o.o.o.o.o.o.{ ",
"  7.7.7.7.7.7.7.7.7.7.7.7.{ t z.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.T 6.A.B., C.l.e.#.o.7.7.7.7.7.7.7.7.7.7.7.7.7.u.",
"  * * * * * * * * * * * * u.} z.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.T q E # i 0.D.E.o.* * * * * * * * * * * * * o ",
"  * { { { { { { { { { { { u.} z.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.;.Z |.N ^ 7 F.G.*...{ { { { { { { { { { { * o ",
"  { { { { { { { { { { { { o + R ;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.}.;.T u H.B.#.9 I.x.* { { { { { { { { { { { { i ",
"  u.u.u.u.u.u.u.u.u.u.u.u.i + R ;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.v >.p.{ z y 7.u.u.u.u.u.u.u.u.u.u.u.u.u.F ",
"  o o o o o o o o o o o o F g R ;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.T Z b.J.u.a.7.o o o o o o o o o o o o o o P ",
"  i i i i i i i i i i i i P _ R ;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.v q t.) = K.i i i i i i i i i i i i i i i L.",
"  F F F F F F F F F F F F L.| R ;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.T 6.w h.I n i F F F F F F F F F F F F F F F #.",
"  F F F F F F F F F F F F L.| R ;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.T T J U p.t '.i P F F F F F F F F F F F F F F F #.",
"  P L.L.L.L.L.L.L.L.L.L.L.#.' K T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T Z >.n.< @.#.P L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.P K.",
"  L.L.L.L.L.L.L.L.L.L.L.L.K.' K T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T Z q i.b * n L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.K.",
"  #.#.#.#.#.#.#.#.#.#.#.#.@.p K T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T v 6.g.~.' 2.L.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.@.",
"  #.K.K.K.K.K.K.K.K.K.K.K.@./ K v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v T v v u b.1.& M.#.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.#.x.",
"  K.K.K.K.K.K.K.K.K.K.K.K.x.B S v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v J M 9.) #.= K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.= ",
"  @.x.x.x.x.x.x.x.x.x.x.x.= I S v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v Z %.{.N.].M.@.x.x.x.x.x.x.x.x.x.x.x.x.x.x.x.x.x.x.x.@.O.",
"  x.x.x.x.x.x.x.x.x.x.x.x.O.I K v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v v 6.l s g q.@.x.x.x.x.x.x.x.x.x.x.x.x.x.x.x.x.x.x.x.x.x.n ",
"  = = = = = = = = = = = = n Q C Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z J 6.b.N - '.x.= = = = = = = = = = = = = = = = = = = = = = n ",
"  O.O.O.O.O.O.O.O.O.O.O.O.. c S Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z J M E # L.2.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.. ",
"  O.O.O.O.O.O.O.O.O.O.O.O.'.c S Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z J q ` s.c q.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.'.",
"  n . . . . . . . . . . . M., C J J J J J J J J J J J J J J J J J J J J J J J J J J J J J J J J J Z Z Z Z Z Z Z Z Z Z Z Z 6.!.c.: P.n . . . . . . . . . . . . . . . . . . . . . . . n M.",
"  . . . . . . . . . . . . 2.).L u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u J Z J J J J J J J Z J u |.n.@ . '.. . . . . . . . . . . . . . . . . . . . . . . . . M.",
"  '.'.'.'.'.'.'.'.'.'.'.'.2.].J M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M u J J J J J J J J J u M i.b i q.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.2.",
"  M.M.M.M.M.M.M.M.M.M.M.M.d.7.r g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.w %.J J J J J J J J u %.w 3.p P.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.d.",
"  2.2.2.2.2.2.2.2.2.2.2.2.d.x.: + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + g @ > g.J J J J J J D U 1.! P.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.d.",
"  2.d.d.d.d.d.d.d.d.d.d.d.d.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.P.Q.6.J J u J 6.|._.) x.R.2.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.2.R.",
"  d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.7 Q.D u u u 6.M S.N.7.7 d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.R.",
"  R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.W Q.D u u 6.%.g.V g W R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.0 ",
"  q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.k c.6.u u D b.h 1 q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.P.",
"  q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.=.s D u 6.>.E T.K.7 0 q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.P.",
"  0 P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.U.~.%.6.m.A.s., k P.0 P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.0 7 ",
"  P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.H ~.%.%.H.p.: =.7 P.7 P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.W ",
"  7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 H 3.m.b.n.@ 2.P.7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 W ",
"  W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W d V.r t.W.F U.W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W =.",
"  k k k k k k k k k k k k k k k k k k k k k k k k k k k k k k k k k k k k k k k k k k k k k k k k k C.B.S.V./ U.k k k k k k k k k k k k k k k k k k k k k k k k k k k k k k k k k k k =.",
"  =.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.y b p.! k =.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.U.",
"  =.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.C.~ ] n U.U.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.U.",
"  U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.C.p { C.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.H ",
"  H H H H H H H H H H H H H H H H H H H H H H H H H H H H H H H H H H H H H H H H H H H H H H H H H d @.C.d H H H H H H H H H H H H H H H H H H H H H H H H H H H H H H H H H H H H d   ",
"  y d d d d d d d d d d d d d d d d d d d d d d d d d d d d d d d d d d d d d d d d d d d d d d d d d a.C.d d d d d d d d d d d d d d d d d d d d d d d d d d d d d d d d d d d d d C.  ",
"    d d C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.d d C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.d y   ",
"    y C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.y     ",
"    [.y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y +.    ",
"      ^.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.^.      ",
"        5 ^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.[.      ",
"          5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 k.        ",
"            [.5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 [.5 [.a.          ",
"              a.[.k.[.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.[.[.k.              ",
"                  a.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.a.j                 ",
"                        v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.j                         "};
