/* XPM */
static const char * browser_home_xpm[] = {
"77 77 202 2",
"  	c None",
". 	c #8B95A8",
"+ 	c #9DA9C0",
"@ 	c #ABB7D0",
"# 	c #8893A8",
"$ 	c #9DA9C1",
"% 	c #B8C6E0",
"& 	c #BDCCE6",
"* 	c #ABB9D2",
"= 	c #B8C6E1",
"- 	c #C7D6F2",
"; 	c #C9D9F4",
"> 	c #BBCAE4",
", 	c #D5E5FD",
"' 	c #D4E4FD",
") 	c #DEEEFF",
"! 	c #D8E7FF",
"~ 	c #D1E1FD",
"{ 	c #DFEFFF",
"] 	c #D7E6FF",
"^ 	c #D3E3FF",
"/ 	c #9DAAC1",
"( 	c #DDEDFF",
"_ 	c #D6E6FF",
": 	c #D3E2FF",
"< 	c #8892A7",
"[ 	c #DBEBFF",
"} 	c #D6E5FF",
"| 	c #DAE9FF",
"1 	c #D5E3FF",
"2 	c #D3E1FF",
"3 	c #D7E7FF",
"4 	c #D2E0FD",
"5 	c #D3E0FE",
"6 	c #9DAAC2",
"7 	c #D3E2FE",
"8 	c #CFDDFA",
"9 	c #D0DEFC",
"0 	c #D6E5FD",
"a 	c #CFDEFA",
"b 	c #CCDAF7",
"c 	c #CEDBF9",
"d 	c #C8D7F2",
"e 	c #CCDAF6",
"f 	c #C9D7F3",
"g 	c #CBD9F5",
"h 	c #DFEEFF",
"i 	c #C8D6F2",
"j 	c #C6D4F0",
"k 	c #9DABC2",
"l 	c #C8D7F3",
"m 	c #C4D2EE",
"n 	c #C3D1ED",
"o 	c #C5D3EF",
"p 	c #8892A6",
"q 	c #C2D1ED",
"r 	c #C2D0EC",
"s 	c #B8C6E2",
"t 	c #9DABC3",
"u 	c #B9C6E2",
"v 	c #C4D2ED",
"w 	c #D6E6FD",
"x 	c #C1CFEB",
"y 	c #C0CEE9",
"z 	c #C0CEEA",
"A 	c #C3D1EC",
"B 	c #8893A7",
"C 	c #B9C7E2",
"D 	c #C6D5F1",
"E 	c #BCCAE5",
"F 	c #BBC9E4",
"G 	c #BECCE8",
"H 	c #CBD8F6",
"I 	c #8793A6",
"J 	c #D2E2FB",
"K 	c #C5D4EF",
"L 	c #B7C5E0",
"M 	c #BFCEE9",
"N 	c #C1D0EC",
"O 	c #BFCDE9",
"P 	c #B9C7E1",
"Q 	c #C2D0ED",
"R 	c #CFDCFA",
"S 	c #D0DFF6",
"T 	c #B4C1DC",
"U 	c #B6C4DF",
"V 	c #BECDE9",
"W 	c #C0CFEB",
"X 	c #BAC8E4",
"Y 	c #C3D1EB",
"Z 	c #8691A5",
"` 	c #C6D5EB",
" .	c #B7C4DD",
"..	c #B2BFD9",
"+.	c #B4C2DB",
"@.	c #BCCCE8",
"#.	c #BFCFEB",
"$.	c #BCCAE6",
"%.	c #B5C2DD",
"&.	c #C3D0EB",
"*.	c #D3E2F5",
"=.	c #BBC9DF",
"-.	c #B6C3DA",
";.	c #B1BED6",
">.	c #B3C0D8",
",.	c #B9C7E3",
"'.	c #B3C1DB",
").	c #C2CFEA",
"!.	c #C6D4E8",
"~.	c #B6C2D8",
"{.	c #B0BBD2",
"].	c #B0BED5",
"^.	c #BACAE5",
"/.	c #B4C2DC",
"(.	c #B0BDD5",
"_.	c #BDC9E3",
":.	c #BFCDE6",
"<.	c #B9C7E0",
"[.	c #ADB7CE",
"}.	c #A1ACBF",
"|.	c #9AA5BA",
"1.	c #A0AAC0",
"2.	c #B1BFDA",
"3.	c #B6C5E1",
"4.	c #AEBDD5",
"5.	c #A5B3CA",
"6.	c #A0ABBF",
"7.	c #ACB7CF",
"8.	c #B5C3DC",
"9.	c #9DA8BF",
"0.	c #838B9D",
"a.	c #7C8496",
"b.	c #858DA0",
"c.	c #A1ADC6",
"d.	c #B1BFDB",
"e.	c #919CAE",
"f.	c #96A1B6",
"g.	c #A2AEC7",
"h.	c #8792A6",
"i.	c #939CB2",
"j.	c #8D97AA",
"k.	c #858C9F",
"l.	c #848C9F",
"m.	c #828A9D",
"n.	c #82899C",
"o.	c #81899B",
"p.	c #81889B",
"q.	c #798191",
"r.	c #909AAF",
"s.	c #A5B1CA",
"t.	c #929EB3",
"u.	c #7B8495",
"v.	c #8A92A6",
"w.	c #8893A5",
"x.	c #606876",
"y.	c #959FB4",
"z.	c #6B7583",
"A.	c #0F0F0F",
"B.	c #616976",
"C.	c #626A78",
"D.	c #636B79",
"E.	c #656D7B",
"F.	c #666F7D",
"G.	c #676F7E",
"H.	c #67707E",
"I.	c #68717F",
"J.	c #BFCDE8",
"K.	c #BDCCE7",
"L.	c #BDCCE8",
"M.	c #B7C5DF",
"N.	c #BBC9E5",
"O.	c #B9C8E4",
"P.	c #B5C3DD",
"Q.	c #B6C5DF",
"R.	c #B4C1D9",
"S.	c #B2BFD8",
"T.	c #B3C1D9",
"U.	c #B2BFD7",
"V.	c #B1BED5",
"W.	c #AFBCD5",
"X.	c #AFBBD2",
"Y.	c #AEBAD1",
"Z.	c #ADB9D1",
"`.	c #A5B2C9",
" +	c #9CA7BD",
".+	c #99A3B6",
"++	c #96A1B5",
"@+	c #97A3B5",
"#+	c #919DB0",
"$+	c #868EA2",
"%+	c #7C8494",
"&+	c #788091",
"*+	c #7C8495",
"=+	c #68727F",
"-+	c #666D7A",
";+	c #838C9F",
">+	c #7F879A",
",+	c #7D8698",
"'+	c #7E8698",
")+	c #7E8799",
"!+	c #80899B",
"~+	c #6C7481",
"                                                                                                                                                          ",
"                                                                                                                                                          ",
"                                                                                                                                                          ",
"                                                                                                                                                          ",
"                                                                                                                                                          ",
"                                                                              .                                                                           ",
"                                                                            + @ #                                                                         ",
"                                                                          $ % & * #                                                                       ",
"                                                                        $ = - ; > * #                                                                     ",
"                                                                      $ = - , ' - > * #                                                                   ",
"                                                                    $ = - , ) ! ~ - > * #                                                                 ",
"                                                                  $ = - , ) { ] ^ ~ - > * #                                                               ",
"                                                                / = - , ) { ( _ : ^ ~ - > * <                                                             ",
"                                                              + = - , ) { ( [ } : : ^ ~ - > * <                                                           ",
"                                                            $ = - , ) { ( [ | 1 2 : : ^ ~ - > * <                                                         ",
"                                                          $ = - , ) { ( [ | 3 4 5 2 : : ^ ~ - > * <                                                       ",
"                                                        6 = - , ) { ( [ | 3 7 8 9 5 2 : : ^ ~ - > * <                                                     ",
"                                                      6 = - 0 ) { ( [ | 3 7 a b c 9 5 2 : : ^ ~ - > * #                                                   ",
"                                                    6 = d 0 ) { ( [ | 3 7 a e f g c 9 5 2 : : ^ ~ - > * #                                                 ",
"                                                  6 = d 0 ) h ( [ | 3 7 a e i j i g c 9 5 2 : : ^ ~ - > * #                                               ",
"                                                k = l 0 ) h ( [ | 3 7 a e i m n o i g c 9 5 2 : : ^ ~ - > * p                                             ",
"                                              6 = l 0 ) h ( [ | 3 7 a e i m q r r o i g c 9 5 2 : : ^ ~ - > * p                                           ",
"                                            6 s l 0 ) h ( [ | 3 7 a e i m q r r r r o i g c 9 5 2 : : ^ ~ - > * p                                         ",
"                                          6 s l 0 ) h ( [ | 3 7 a e i m q r r r r r r o i g c 9 5 2 : : ^ ~ - > * p                                       ",
"                                        t u l 0 ) h ( [ | 3 7 a e i m q r r r r r r r r v i g c 9 5 2 : : ^ ~ - > * p                                     ",
"                                      t u l w ) h ( [ | 3 7 a i x y x r r r r r r r r r z y A f c 9 5 2 : : ^ ~ - > * B                                   ",
"                                    t C l w ) h ( [ | 3 7 D E F E z r r r r r r r r r r x G F F A H 9 5 2 : : ^ ~ - > * I                                 ",
"                                  t C l w ) h ( [ | J K C L L = M N r r r r r r r r r r x O E L L L P Q R 2 : : ^ ~ - > * I                               ",
"                                t C l w ) h ( [ S % T T T T U V W N r r r r r r r r r r x O V X T T T T T Y 8 : : ^ ~ - > * Z                             ",
"                              6 C l w ) h ( `  ...........+.@.#.W N r r r r r r r r r r x O V $.L ............%.&.: ^ ~ - > * Z                           ",
"                            6 C l w ) *.=.-.;.;.;.;.;.;.>.,.V #.W N r r r r r r r r r r x O V $.C '.;.;.;.;.;.;.;.;.).a ~ - > * Z                         ",
"                          6 C l w !.~.{.{.{.{.{.{.{.{.].U ^.V #.W N r r r r r r r r r r x O V $.C /.(.{.{.{.{.{.{.{.{.{._.:.- > * Z                       ",
"                        t C <.[.}.|.|.|.|.|.|.|.|.|.1.2.3.^.V #.W N r r r r r r r r r r x O V $.C /.4.5.|.|.|.|.|.|.|.|.|.|.6.7.8.* Z                     ",
"                      t 9.0.a.a.a.a.a.a.a.a.a.a.a.b.c.d.3.^.V #.W N r r r r r r r r r r x O V $.C /.4.5.e.a.a.a.a.a.a.a.a.a.a.a.a.f.g.h.                  ",
"                    i.j.k.l.0.m.n.n.o.o.o.o.p.p.q.r.s.d.3.^.V #.W N r r r r r r r r r r x O V $.C /.4.5.t.u.p.p.o.o.o.o.o.n.m.0.l.k.k.v.w.                ",
"                                                x.y.s.d.3.^.V #.W N r r r r r r r r r r x O V $.C /.4.5.t.z.A.                                            ",
"                                                B.y.s.d.3.^.V #.W N r r r r r r r r r r x O V $.C /.4.5.t.z.                                              ",
"                                                C.y.s.d.3.^.V #.W N r r r r r r r r r r x O V $.C /.4.5.t.z.                                              ",
"                                                D.y.s.d.3.^.V #.W N r r r r r r r r r r x O V $.C /.4.5.t.z.                                              ",
"                                                E.y.s.d.3.^.V #.W N r r r r r r r r r r x O V $.C /.4.5.t.z.                                              ",
"                                                F.y.s.d.3.^.V #.W N r r r r r r r r r r x O V $.C /.4.5.t.z.                                              ",
"                                                G.y.s.d.3.^.V #.W N r r r r r r r r r r x O V $.C /.4.5.t.z.                                              ",
"                                                H.y.s.d.3.^.V #.W N r r r r r r r r r r x O V $.C /.4.5.t.z.                                              ",
"                                                I.y.s.d.3.^.V #.W N r r r r r r r r r r x O V $.C /.4.5.t.z.                                              ",
"                                                I.y.s.d.3.^.V #.W N r r r r r r r r r r x O V $.C /.4.5.t.z.                                              ",
"                                                I.y.s.d.3.^.V #.W N r r r r r r r r r r x O V $.C /.4.5.t.z.                                              ",
"                                                I.y.s.d.3.^.V #.W N r r r r r r r r r r x O V $.C /.4.5.t.z.                                              ",
"                                                I.y.s.d.3.^.V #.W N r r r r r r r r r r x O V $.C /.4.5.t.z.                                              ",
"                                                I.y.s.d.3.^.V #.W N r r r r r r r r r r x O V $.C /.4.5.t.z.                                              ",
"                                                I.y.s.d.3.^.V #.W N r r r r r r r r r r x O V $.C /.4.5.t.z.                                              ",
"                                                I.y.s.d.3.^.V #.W N r r r r r r r r r r x O V $.C /.4.5.t.z.                                              ",
"                                                I.y.s.d.3.^.V #.W N r r r r r r r r r r x O V $.C /.4.5.t.z.                                              ",
"                                                I.y.s.d.3.^.V #.W N r r r r r r r r r r x O V $.C /.4.5.t.z.                                              ",
"                                                I.y.s.d.3.^.V #.W N r r r r r r r r r r x O V $.C /.4.5.t.z.                                              ",
"                                                I.y.s.d.3.^.V #.W N r r r r r r r r r r x O V $.C /.4.5.t.z.                                              ",
"                                                I.y.s.d.3.^.V #.W M J.J.J.J.J.J.J.J.J.J.J.O V $.C /.4.5.t.z.                                              ",
"                                                I.y.s.d.3.^.V #.K.F F F F F F F F F F F F F L.$.C /.4.5.t.z.                                              ",
"                                                I.y.s.d.3.^.V $.L M.M.M.M.M.M.M.M.M.M.M.M.M.L N.C /.4.5.t.z.                                              ",
"                                                I.y.s.d.3.^.O.8.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.P.= /.4.5.t.z.                                              ",
"                                                I.y.s.d.3.Q.R.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.T.+.4.5.t.z.                                              ",
"                                                I.y.s.d.T U.V.V.V.V.V.V.V.V.V.V.V.V.V.V.V.V.V.V.V.;.4.5.t.z.                                              ",
"                                                I.y.s.W.X.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Z.`.t.z.                                              ",
"                                                I.y. +.+++++++++++++++++++++++++++++++++++++++++++++++@+#+z.                                              ",
"                                                I.$+%+&+&+&+&+&+&+&+&+&+&+&+&+&+&+&+&+&+&+&+&+&+&+&+&+&+*+=+                                              ",
"                                                -+;+>+,+,+,+,+,+,+,+,+,+,+,+,+,+,+,+,+,+,+,+,+,+,+,+'+)+!+~+                                              ",
"                                                                                                                                                          ",
"                                                                                                                                                          ",
"                                                                                                                                                          ",
"                                                                                                                                                          ",
"                                                                                                                                                          ",
"                                                                                                                                                          ",
"                                                                                                                                                          ",
"                                                                                                                                                          ",
"                                                                                                                                                          ",
"                                                                                                                                                          ",
"                                                                                                                                                          ",
"                                                                                                                                                          "};
